### ISSUE TITLE
it no w

### ISSUE THREAD

**Issue by cartben656** [bogachenko/filterlist#4]
plz fix
https://news.xbox.com/en-us/2021/10/29/new-games-with-gold-for-november-2021/

**Comment by bogachenko** [comment]
what to fix? This repository is not for public use.

**Comment by bogachenko** [comment]
what should I fix and where?

**Comment by cartben656** [comment]
i go to https://news.xbox.com/en-us/2021/10/29/new-games-with-gold-for-november-2021/
i get wite scren notng eve lods
ublok orign with this lit + fukfuckadlock + deault ublock stuf

**Comment by cartben656** [comment]
thiz wat i see
<img width="571" alt="whit sceen" src="https://github.com/bogachenko/filterlist/assets/153392955/edbb9200-0ac0-4d7d-ac0c-8f907307b9d3">

**Comment by cartben656** [comment]
jst blnk page nthing eveh lod

**Comment by cartben656** [comment]
sry

**Comment by bogachenko** [comment]
I can't reproduce it. I would not recommend using this repository, as it was not created for widespread use.
I still don't understand what and where you added, because the files `bogachenkoBL.dns` and `bogachenkoWL.dns` is designed to block domains at the DNS level, it uses regular expressions that will be used incorrectly in advanced adblockers such as uBO.
_These sheets can be used in programs such as AdGuard Home, or Pinhole and similar programs._

The bogachenkoBL.hosts file was created for hosts.txt . This is also a DNS-level lock, but only more limited than what I described above. When using it, errors may also occur (for example, with my sheet - Fuck Fuck adblock), because advertising domains that may be required in Fuck Fuckadblock are blocked there.
_It is used for any editor programs hosts.txt. For example, I use it on my phone, through the AdAway program_

And finally, bogachenkoPF.txt is for uBO and for Adguard. But there are a lot of specific rules mixed in there, some of them can and will break the markup of sites. There I test and use specific rules, it is NOT RECOMMENDED to use it with Fuck Fuck adblock - there will be false positives of antiadblock.
_used in Adguard for Android, Adguard for windows, uBlock Origin_

**Comment by cartben656** [comment]
ok remvoed
sry
